### ISSUE TITLE
Create Global CSS File

### ISSUE THREAD

**Issue by dfols** [dfols/admas#13]
1. Create a folder named `styles` in the root directory of the project if it doesn't already exist.
2. Create a new file named `global.css` inside the `styles` folder.
3. Add the following CSS Reset to the `global.css` file:
   ```css
   /*
     Josh's Custom CSS Reset
     https://www.joshwcomeau.com/css/custom-css-reset/
   */
   *, *::before, *::after {
     box-sizing: border-box;
   }
   * {
     margin: 0;
   }
   body {
     line-height: 1.5;
     -webkit-font-smoothing: antialiased;
     font-family: sans-serif;
   }
   img, picture, video, canvas, svg {
     display: block;
     max-width: 100%;
   }
   input, button, textarea, select {
     font: inherit;
   }
   p, h1, h2, h3, h4, h5, h6 {
     overflow-wrap: break-word;
   }
   ```
